# Generated by Django 4.0.2 on 2022-09-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uploadfile', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
