# Generated by Django 4.0.2 on 2022-10-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uploadfile', '0002_remove_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='img',
        ),
    ]
