# Generated by Django 4.0.2 on 2022-10-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uploadfile', '0003_rename_image2_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
